# Generated by Django 4.2.9 on 2024-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motesh',
        ),
    ]
