# Generated by Django 4.2.9 on 2024-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_delete_motesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
