# Generated by Django 4.2.9 on 2024-02-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
