# Generated by Django 4.2.9 on 2024-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_date',
            field=models.CharField(default='', max_length=150),
        ),
    ]
